// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaQMPbhOObe0Ril4PzxKgvYBqj9Q5SLdA',
    appId: '1:277520899434:web:c891d1fd37c2a62d1ad913',
    messagingSenderId: '277520899434',
    projectId: 'bitebuddies-fd29b',
    authDomain: 'bitebuddies-fd29b.firebaseapp.com',
    storageBucket: 'bitebuddies-fd29b.appspot.com',
    measurementId: 'G-E0F62NW3B8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5r7xE582eJiPOr9PFw42RvyFTr-Tgssk',
    appId: '1:277520899434:android:df4568963522ac9b1ad913',
    messagingSenderId: '277520899434',
    projectId: 'bitebuddies-fd29b',
    storageBucket: 'bitebuddies-fd29b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFrsjjZpN95dQ63TOVLXVC-lydTt0PVOw',
    appId: '1:277520899434:ios:95f2fe0652928ce31ad913',
    messagingSenderId: '277520899434',
    projectId: 'bitebuddies-fd29b',
    storageBucket: 'bitebuddies-fd29b.appspot.com',
    iosClientId: '277520899434-1poq8jt1ud3e6tgan1jap2blak13uijk.apps.googleusercontent.com',
    iosBundleId: 'com.example.monkeyAppDemo',
  );
}
